### ISSUE TITLE
Package can't be imported

### ISSUE THREAD

**Issue by rrrene** [atlas-engine/AdminClient.ts#2]
Wenn ich das Paket einbinde, erhalte ich folgende Meldung:

```shell
$ tsc && ./dist/atlas.js
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '@atlas-engine/event_aggregator_contracts'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/rrrene/projects/atlas-engine/cli/node_modules/@atlas-engine/atlas_engine_admin_client/dist/commonjs/clients/socket_io_manager.js:6:38)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

Das Paket `@atlas-engine/event_aggregator_contracts` ist unter `devDependencies` gelistet.

**Comment by ElRaptorus** [comment]
Fixed in https://github.com/atlas-engine/AdminClient.ts/commit/7e29274370efafd4d82851d8b9aee7d9ffdd35f7

**Comment by rrrene** [comment]
Funktioniert! 👍
